### ISSUE TITLE
feat: support COMMIT_EDITMSG

### ISSUE THREAD

**Issue by cafkafk** [convco/convco#157]
**Is your feature request related to a problem? Please describe.**
In the same vein as #146, but here specifically when something like e.g. [pre-commit-hooks](https://pre-commit.com/) fail.

**Describe the solution you'd like**
The commit msg you edit should be the `.git/COMMIT_EDITMSG`. That way, if an operation fails, you can recover the commitmessage.

**Describe alternatives you've considered**
I couldn't come up with any alternatives.

**Additional context**
https://git-scm.com/docs/git-commit/2.2.3#Documentation/git-commit.txt-codeGITDIRCOMMITEDITMSGcode

**Comment by hdevalke** [comment]
As I understand it, convco should read `COMMIT_EDITMSG` and if it exist and is valid, use it instead of prompting the user for input.

**Comment by cafkafk** [comment]
Hmm, I understood it as existing more as a place to store a commit message if a commit action failed, and that it would be overwritten by the next attempt at committing.

> This file contains the commit message of a commit in progress. If git commit exits due to an error before creating a commit, any commit message that has been provided by the user (e.g., in an editor session) will be available in this file, but will be overwritten by the next invocation of git commit.

**Comment by hdevalke** [comment]
Indeed, when git uses an editor it will open and truncate the `.git/COMMIT_EDITMSG` file. When the editor has saved the file, git will read the contents to read the content as the commit message.

In order to continue with this message after a commit failed, you have to run: 

```sh
git commit -e --file=$(git rev-parse --git-dir)/COMMIT_EDITMSG
```

Convco is not run as  an editor for git, but calls git with the conventional message. As a consequence the message is not saved when the pre-commit hook failed.

> The pre-commit hook is run first, before you even type in a commit message.

I see 2 solutions:

1) convco commit can be used as a git editor, but this needs to make it work with a file argument to edit:
     GIT_EDITOR='convco commit' git commit --edit
     hint: Waiting for your editor to close the file... error: unexpected argument '/../convco/.git/COMMIT_EDITMSG' found
     
     Usage: convco commit [OPTIONS] [-- <EXTRA_ARGS>...]
     
     For more information, try '--help'.
     error: There was a problem with the editor 'convco commit'.
     Please supply the message using either -m or -F option.
2) convco implements the logic to write the results to `.git/COMMIT_EDITMSG` or `.git/convco_msg` and then calls `git commit`. It can recover from this file if it removes the file on a successfull git commit, as git is not cleaning up this file.

Any preferences?

**Comment by cafkafk** [comment]
I think option two is better IMO, not sure whether `.git/COMMIT_EDITMSG` or `.git/convco_msg` is best thou.

**Comment by hdevalke** [comment]
I think both can work with` .git/convco_msg` as default backup file. If the file exists and is a valid commit message convco will ask to accept/edit/reject it. The file will be removed if git was run successfully, unless it is `.git/COMMIT_EDITMSG` where convco will not call git commit as git will read it's contents to make the commit.

**Comment by hdevalke** [comment]
@cafkafk would you mind to test/review #159 ? It is a bit hacked together but it does what it needs to do.

**Comment by cafkafk** [comment]
> @cafkafk would you mind to test/review #159 ? It is a bit hacked together but it does what it needs to do.

Yes sure thing!
