### ISSUE TITLE
Support http repository host in changelog links

### ISSUE THREAD

**Issue by ite-klass** [convco/convco#68]
The generated changelog creates links to version tags, commits, and tag-diff-commit-list.

The host and repository path seem to be determined in `host_info_from_url`, which prepends https to the host.

This means the produced changelog always uses https links even when that is not available - when http is used.

It would be nice if convco would support http-hosted GitLab too.

*(At the users discretion, HTTP instead of HTTPS may be excusable for intranets of trusted parties or read-only viewing of these version and commit information.)*

**Comment by hdevalke** [comment]
The reason to use https is probably because i mainly use https hosts and for the git I use an ssh connection.

```
❯ git remote get-url origin 
git@github.com:convco/convco.git
```

There is no information in the origin url to know if the hosting platform is using http or https.
maybe an optional `hostSchema` in config could be set to use `http` or any other protocol of choice, but defaults to `https`

**Comment by hdevalke** [comment]
https://github.com/convco/convco/pull/69 fixes it partly if http is used as git remote protocol. but will still fail if ssh is used and the host platform is using http for the web UI.
