### ISSUE TITLE
Template commit subjects have added linebreaks (Markdown + LF line breaks)

### ISSUE THREAD

**Issue by Kissaki** [convco/convco#84]
Using a --template template.hbs, commit title seems to have newlines added (with `  \n` markdown + unix newline) on width excedding 86(?) characters.

For a template with `\r\n` (CR LF) newlines, the added `\n` newlines lead to mixed EOL of the text document.

Adding the Markdown two-space-line-break prevents template customization from being potentially useful for alternative output formats.

Writing the template file I would not have expected newlines to be added.

Reading the changelog as text, the broken line continuing without indentation makes it subjectively harder to read - even if/while rendered Markdown renders it indented.

Git commit summaries are supposed to be short when creating them. If they are designed and written by the author in a narrowed environment, it seems unnecessary to impose own, potentially different length rules that lead to different output.

---

I adjusted the template to be a list of commit summaries. It may be more obvious in this case over the default template with additional information.

```
* commit 1
* commit 2 aaaaaaaaa aaaaaaaaa aaaaaaaaa aaaaaaaaa 
aaaaaaaaa (Ticket)
* commit 3
```

---

I suggest filling `commits` `subject` without adding line breaks to them. I see no downsides in rendering as-is. But as argued, I see various downsides of different degrees in adding newlines.

**Comment by hdevalke** [comment]
Word wrap has been added here 3338cf2ef5ce5addf054571ad4e3ef215f7e4b3d. 

You can probably play with the line length config. Maybe it is better to remove this wrapping, but enforce a max length in the `commit` and `check` subcommands.

```
# file: .versionrc
lineLength: 999
```

**Comment by Kissaki** [comment]
The `.versionrc` setting `lineLength: 999` indeed resolves my immediate issue.

Feel free to close this ticket or keep it open if you plan to do something on this or not.

**Comment by hdevalke** [comment]
I think it would be better to move the word wrap logic to a handlebars helper.
Such that:

- it can wrap `type(scope): description` instead of only taking `description` into account.
- it can also be used to wrap the body

The word wrap could be applied when doing `convco commit` too. I'll keep the ticket open for now

**Comment by hdevalke** [comment]
I added the option to disable word wrap for the default template, or if you use a custom template, the word-wrap will not be done if you do not use the `{{#word-wrap}}..{{/word-wrap}}` handlebars block.

For the newlines I think one solution could be to pass in `convco changelog | unix2dos > CHANGELOG.md` should work. Or maybe with a `.gitattributes` file, git can fix the line ending issues (see https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings).

If you think i should do something more for this ticket please tell, otherwise i will close it soon.

**Comment by Kissaki** [comment]
You say it defaults to no word wrapping, but looking at commit 0fa3ea49d0973710af13ad99221715b84a4458a5 I see `--no-wrap` is introduced to disable wrapping, and the default value `wrap_disabled: false,` [1](https://github.com/convco/convco/commit/0fa3ea49d0973710af13ad99221715b84a4458a5#diff-7e1527026b13d18c6db5943a64a0612698b938f7c01392e00a407532ee13e628R119)[2](https://github.com/convco/convco/commit/0fa3ea49d0973710af13ad99221715b84a4458a5#diff-7e1527026b13d18c6db5943a64a0612698b938f7c01392e00a407532ee13e628R428) seems to indicate that it defaults to wrapping? Could you clarify that?

**Comment by hdevalke** [comment]
> You say it defaults to no word wrapping

In case you use a default template and do not use a word-wrap block (see [commit.hbs:1](https://github.com/convco/convco/blob/master/src/conventional/changelog/commit.hbs#L1)) no wrapping will be performed.

**Comment by Kissaki** [comment]
Ah, so if the template does not have the `word-wrap` block neither the config nor `--no-wrap` willy have any effect?

Awesome, thank you. I will be using the new default behavior - of no line breaks at all.

Regarding line endings `unix2dos` may not be available on Windows, and a `.gitattributes` approach will only be able to fix to consistent line endings after file commit and modified file checkout, but for me personally that is of no practical concern rn (given that I am not using wrapping). Feel free to close.
